apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    app.ktool.io/short-uuid: "1"
    app.ktool.io/type: script
  generateName: ktool-script-
  labels:
    ktool-app: "true"
    script-extension: sh
  namespace: test
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - command:
        - bin/sh
        - /ktool/script.sh
        image: busybox
        imagePullPolicy: Always
        name: ktool-script
        resources: {}
        volumeMounts:
        - mountPath: /ktool
          name: ktool-scripts
      restartPolicy: Never
      volumes:
      - configMap:
          defaultMode: 511
          name: ktool-script-1
        name: ktool-scripts
  ttlSecondsAfterFinished: 10
status: {}