apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    app.ktool.io/short-uuid: 16db7
    app.ktool.io/type: script
  generateName: ktool-script-16db7-
  labels:
    app: myapp
    ktool-app: "true"
    script-extension: sh
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: myapp
      name: myapp
    spec:
      containers:
      - args:
        - -t
        - "1"
        - -aux
        command:
        - /bin/sh
        - -c
        - /ktool/script.sh
        env:
        - name: ENV_NAME
          value: ENV_VALUE
        image: busybox
        imagePullPolicy: Always
        name: ktool-script
        resources: {}
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /ktool
          name: ktool-scripts
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: localtime
      - configMap:
          defaultMode: 511
          name: ktool-script-16db7
        name: ktool-scripts
  ttlSecondsAfterFinished: 10
status: {}

---
apiVersion: v1
data:
  script.sh: |-
    echo "hola1"
    sleep 2
    echo "hola2"
    sleep 2
    echo "hola3"
    # exit 1
    sleep 2
    echo "hola4"
    sleep 2
    echo "hola5"
    sleep 2
    echo "hola6"
    sleep 2
    echo "hola7"
    sleep 2
    echo "hola8"
kind: ConfigMap
metadata:
  name: ktool-script-16db7
  namespace: default