apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  labels:
    app: test
spec:
  template:
    metadata:
      name: test
      labels:
        app: test
      annotations:
        example: "test"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disktype
                    operator: In
                    values:
                      - ssd
      containers:
      - name: "python"
        image: python:3.6
        command: ['sh', '-c', 'python3 test.py']
        env:
        - name: ENV_NAME
          value: ENV_VALUE
        
        volumeMounts:
        - name: test
          mountPath: /test

      volumes:
      - name: test
        hostPath:
          path: /test
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst